language: android
jdk: oraclejdk7
android:
  components:
    # - platform-tools
    # - tools
    - build-tools-23.0.1
    - android-23
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - addon-google_apis-google-23